// ============================================================
// vue-base-components — 共享组件库统一入口
// ============================================================

// ── 业务组件 ──────────────────────────────────────────────
export { default as BaseTable } from './components/BaseTable.vue'
export type { Column } from './components/BaseTable.vue'
export { default as BaseEdit } from './components/BaseEdit.vue'
export { default as BasePagination } from './components/BasePagination.vue'
export { default as EditDialog } from './components/EditDialog.vue'
export type { FieldConfig } from './components/EditDialog.vue'
export { default as ImportDialog } from './components/ImportDialog.vue'
export { default as GlobalSearch } from './components/GlobalSearch.vue'
export { default as ComboboxField } from './components/ComboboxField.vue'
export { default as MarkDown } from './components/MarkDown.vue'
export { default as TrendChart } from './components/TrendChart.vue'
export { default as BlurText } from './components/BlurText.vue'

// ── shadcn-vue UI 组件 ────────────────────────────────────
export * from './components/ui/accordion'
export * from './components/ui/alert'
export * from './components/ui/alert-dialog'
export * from './components/ui/aspect-ratio'
export * from './components/ui/attachment'
export * from './components/ui/avatar'
export * from './components/ui/badge'
export * from './components/ui/breadcrumb'
export * from './components/ui/bubble'
export * from './components/ui/button'
export * from './components/ui/button-group'
export * from './components/ui/calendar'
export * from './components/ui/card'
export * from './components/ui/carousel'
export * from './components/ui/chart'
export * from './components/ui/checkbox'
export * from './components/ui/collapsible'
export * from './components/ui/combobox'
export * from './components/ui/command'
export * from './components/ui/context-menu'
export * from './components/ui/dialog'
export * from './components/ui/drawer'
export * from './components/ui/dropdown-menu'
export * from './components/ui/empty'
export * from './components/ui/field'
export * from './components/ui/form'
export * from './components/ui/hover-card'
export * from './components/ui/input'
export * from './components/ui/input-group'
export * from './components/ui/input-otp'
export * from './components/ui/item'
export * from './components/ui/kbd'
export * from './components/ui/label'
export * from './components/ui/marker'
export * from './components/ui/menubar'
export * from './components/ui/message'
export * from './components/ui/message-scroller'
export * from './components/ui/native-select'
export * from './components/ui/navigation-menu'
export * from './components/ui/number-field'
export * from './components/ui/pagination'
export * from './components/ui/pin-input'
export * from './components/ui/popover'
export * from './components/ui/progress'
export * from './components/ui/radio-group'
export * from './components/ui/range-calendar'
export * from './components/ui/resizable'
export * from './components/ui/scroll-area'
export * from './components/ui/select'
export * from './components/ui/separator'
export * from './components/ui/sheet'
export * from './components/ui/sidebar'
export * from './components/ui/skeleton'
export * from './components/ui/slider'
export * from './components/ui/sonner'
export * from './components/ui/spinner'
export * from './components/ui/stepper'
export * from './components/ui/switch'
export * from './components/ui/table'
export * from './components/ui/tabs'
export * from './components/ui/tags-input'
export * from './components/ui/textarea'
export * from './components/ui/toggle'
export * from './components/ui/toggle-group'
export * from './components/ui/tooltip'

// ── 工具函数 ──────────────────────────────────────────────
export { cn } from './lib/utils'
